version: '3.5'
services:
  api1:
    image: thelinuxlich/gleba:latest
    hostname: api1
    depends_on:
      - db
    environment:
      POSTGRES_POOL: 20
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 0.5GB
  api2:
    image: thelinuxlich/gleba:latest
    hostname: api2
    depends_on:
      - db
    environment:
      POSTGRES_POOL: 20
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 0.5GB
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    tmpfs:
      - /tmp/cache:rw,nodev,nosuid,size=400M
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 0.5GB
  db:
    image: postgres:15
    command: postgres -c log_min_messages=FATAL
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
    deploy:
      resources:
        limits:
          cpus: '1.05'
          memory: 1.5GB