version: '3.5'
services:
  api1:
    image: thelinuxlich/gleba:latest
    restart: always
    hostname: api1
    depends_on:
      - db
    environment:
      POSTGRES_POOL: 200
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      ERL_AFLAGS: -sname api1 -setcookie mycookie
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 0.85GB
  api2:
    image: thelinuxlich/gleba:latest
    restart: always
    hostname: api2
    depends_on:
      - db
    environment:
      POSTGRES_POOL: 200
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      ERL_AFLAGS: -sname api2 -setcookie mycookie
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 0.85GB
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 0.2GB
  db:
    image: postgres:15
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1GB