name = "gleba"
version = "0.1.0"
description = "A Gleam project"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
repository = { type = "github", user = "thelinuxlich", repo = "gleba" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.30"
wisp = "~> 0.4"
gleam_pgo = "~> 0.5"
gleam_json = "~> 0.6"
gleam_http = "~> 3.5"
gleam_erlang = "~> 0.20"
mist = "~> 0.13"
ids = "~> 0.8"
ram = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 0.10"
